pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
=> Upgrade cloud Hoxton.SR1 and Boot 2.2.4

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
- Boot 2.3.2.RELEASE
- Cloud Hoxton.SR6
- Fixes #12
=> Upgrade to boot 2.3.x

pom.xml
=> Add testResources build config

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
=> Update boot 2.5.2

spring-cloud-dataflow-build-dependencies/pom.xml
=> Manage spring-shell

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
=> Update Spring Boot 2.5.12 (CVE-2022-22965)

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
=> Update Spring Boot 2.6.6 (CVE-2022-22965)

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
=> Update Spring Boot 2.7.0-RC1 and Spring Cloud 2021.0.02

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
=> Update Spring Boot 2.5.14

spring-cloud-dataflow-build-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5057
cc: @cppwfs @corneil @jvalkeal @markpollack
=> Remove Oracle and DB2 driver version management

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5052
=> Update Spring Boot 2.7.3 + Spring Cloud 2021.0.3

spring-cloud-dataflow-build-dependencies/pom.xml
Fixes spring-cloud/spring-cloud-dataflow#5062
=> Force postgresql 42.4.2 to address CVE

spring-cloud-dataflow-build-dependencies/pom.xml
Fixes spring-cloud/spring-cloud-dataflow#5063
=> Force postgresql 42.2.26 to address CVE

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5125
=> Update Spring Boot 2.7.5

spring-cloud-dataflow-build-dependencies/pom.xml
=> Update Spring Cloud 2021.0.5

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
Fixes vulnerabilities in spring-web and spring-security.
=> Update to Spring Boot 2.7.7

spring-cloud-dataflow-build-dependencies/pom.xml
- Remove previously added Spring Boot BOM as the parent pom has the same effect
=> Update Spring Boot parent to 2.7.7

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5191
=> Update Spring Boot 2.7.8

pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml, spring-cloud-dataflow-dependencies-parent/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
=> Remove repo.spring.io/release

.github/settings.xml, pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml, spring-cloud-dataflow-dependencies-parent/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
=> Add MavenCentral in place of repo.spring.io/release

.github/settings.xml, pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml, spring-cloud-dataflow-dependencies-parent/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
=> Set MavenCentral repo snapshots=false

.mvn/wrapper/maven-wrapper.properties, pom.xml, spring-cloud-dataflow-build-dependencies/pom.xml
Update Spring Boot to 2.7.9, Spring Cloud to 2021.0.6
=> Update Spring Boot to 2.7.9, Spring Cloud to 2021.0.6

pom.xml
Update maven-javadoc-plugin to 3.4.1
Update license-maven-plugin to 1.20
Update sonar-jacoco-listeners to 5.14.0.18788
=> Update maven-failsafe-plugin to 3.0.0-M9
